export const collegesDummyData = [
  {
    _id: "1",
    name: "Anna University, Chennai",
    code: "AU001",
    type: "Government",
    establishedYear: 1978,
    affiliatedUniversity: "Anna University",
    accreditation: {
      naac: "A+",
      nba: true,
    },
    location: {
      state: "Tamil Nadu",
      district: "Chennai",
      city: "Chennai",
      area: "Guindy",
      pincode: "600025",
      coordinates: {
        lat: 13.0107,
        lng: 80.2359,
      },
    },
    contact: {
      email: "info@annauniv.edu",
      phone: "044-2235 7070",
      website: "www.annauniv.edu",
      address: "Sardar Patel Road, Guindy, Chennai",
    },
    admission: {
      admissionProcess: "Entrance Based",
      entranceExams: ["TNEA", "GATE", "TANCET"],
      applicationStartDate: new Date("2024-03-01"),
      applicationEndDate: new Date("2024-05-31"),
    },
    facilities: {
      hostel: true,
      transport: true,
      library: true,
      sports: true,
      wifi: true,
      placementCell: true,
    },
    placement: {
      placementPercentage: 92,
      averagePackage: 650000,
      highestPackage: 3500000,
      topRecruiters: ["TCS", "Infosys", "CTS", "Amazon", "Microsoft"],
    },
    media: {
      logo: "https://example.com/annauniv-logo.jpg",
      images: [
        "https://example.com/college1.jpg",
        "https://example.com/campus1.jpg",
      ],
    },
    isActive: true,
    isVerified: true,
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    _id: "2",
    name: "PSG College of Technology",
    code: "PSG001",
    type: "Private",
    establishedYear: 1951,
    affiliatedUniversity: "Anna University",
    accreditation: {
      naac: "A++",
      nba: true,
    },
    location: {
      state: "Tamil Nadu",
      district: "Coimbatore",
      city: "Coimbatore",
      area: "Peelamedu",
      pincode: "641004",
      coordinates: {
        lat: 11.0168,
        lng: 76.9558,
      },
    },
    contact: {
      email: "principal@psgtech.edu",
      phone: "0422-257 2177",
      website: "www.psgtech.edu",
      address: "Peelamedu, Coimbatore",
    },
    admission: {
      admissionProcess: "Entrance Based",
      entranceExams: ["TNEA"],
      applicationStartDate: new Date("2024-04-01"),
      applicationEndDate: new Date("2024-06-15"),
    },
    facilities: {
      hostel: true,
      transport: false,
      library: true,
      sports: true,
      wifi: true,
      placementCell: true,
    },
    placement: {
      placementPercentage: 95,
      averagePackage: 850000,
      highestPackage: 4200000,
      topRecruiters: ["Google", "Amazon", "IBM", "Bosch", "Zoho"],
    },
    media: {
      logo: "https://example.com/psg-logo.jpg",
      images: [
        "https://example.com/psg-campus.jpg",
        "https://example.com/psg-building.jpg",
      ],
    },
    isActive: true,
    isVerified: true,
    createdAt: new Date("2023-02-10"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    _id: "3",
    name: "SRM Institute of Science and Technology",
    code: "SRM001",
    type: "Deemed",
    establishedYear: 1985,
    affiliatedUniversity: "SRM University",
    accreditation: {
      naac: "A++",
      nba: true,
    },
    location: {
      state: "Tamil Nadu",
      district: "Kancheepuram",
      city: "Chennai",
      area: "Kattankulathur",
      pincode: "603203",
      coordinates: {
        lat: 12.8236,
        lng: 80.0444,
      },
    },
    contact: {
      email: "admission@srmist.edu.in",
      phone: "044-2741 7000",
      website: "www.srmist.edu.in",
      address: "SRM Nagar, Kattankulathur, Chennai",
    },
    admission: {
      admissionProcess: "Entrance Based",
      entranceExams: ["SRMJEEE", "JEE Main"],
      applicationStartDate: new Date("2024-01-15"),
      applicationEndDate: new Date("2024-05-30"),
    },
    facilities: {
      hostel: true,
      transport: true,
      library: true,
      sports: true,
      wifi: true,
      placementCell: true,
    },
    placement: {
      placementPercentage: 90,
      averagePackage: 720000,
      highestPackage: 3800000,
      topRecruiters: ["Amazon", "Microsoft", "Accenture", "Deloitte", "CTS"],
    },
    media: {
      logo: "https://example.com/srm-logo.jpg",
      images: [
        "https://example.com/srm-campus.jpg",
        "https://example.com/srm-hostel.jpg",
      ],
    },
    isActive: true,
    isVerified: true,
    createdAt: new Date("2023-03-05"),
    updatedAt: new Date("2024-01-22"),
  },
  {
    _id: "4",
    name: "Vellore Institute of Technology",
    code: "VIT001",
    type: "Deemed",
    establishedYear: 1984,
    affiliatedUniversity: "VIT University",
    accreditation: {
      naac: "A++",
      nba: true,
    },
    location: {
      state: "Tamil Nadu",
      district: "Vellore",
      city: "Vellore",
      area: "Katpadi",
      pincode: "632014",
      coordinates: {
        lat: 12.8409,
        lng: 79.1536,
      },
    },
    contact: {
      email: "admissions@vit.ac.in",
      phone: "0416-224 3091",
      website: "www.vit.ac.in",
      address: "VIT University, Katpadi, Vellore",
    },
    admission: {
      admissionProcess: "Entrance Based",
      entranceExams: ["VITEEE", "JEE Main"],
      applicationStartDate: new Date("2024-01-01"),
      applicationEndDate: new Date("2024-03-31"),
    },
    facilities: {
      hostel: true,
      transport: true,
      library: true,
      sports: true,
      wifi: true,
      placementCell: true,
    },
    placement: {
      placementPercentage: 94,
      averagePackage: 880000,
      highestPackage: 4500000,
      topRecruiters: [
        "Microsoft",
        "Google",
        "Amazon",
        "Goldman Sachs",
        "JP Morgan",
      ],
    },
    media: {
      logo: "https://example.com/vit-logo.jpg",
      images: [
        "https://example.com/vit-main.jpg",
        "https://example.com/vit-library.jpg",
      ],
    },
    isActive: true,
    isVerified: true,
    createdAt: new Date("2023-01-25"),
    updatedAt: new Date("2024-01-19"),
  },
  {
    _id: "5",
    name: "Madras Institute of Technology",
    code: "MIT001",
    type: "Government",
    establishedYear: 1949,
    affiliatedUniversity: "Anna University",
    accreditation: {
      naac: "A+",
      nba: true,
    },
    location: {
      state: "Tamil Nadu",
      district: "Chennai",
      city: "Chennai",
      area: "Chromepet",
      pincode: "600044",
      coordinates: {
        lat: 12.9516,
        lng: 80.1462,
      },
    },
    contact: {
      email: "dean@mitindia.edu",
      phone: "044-2251 6001",
      website: "www.mitindia.edu",
      address: "Chromepet, Chennai",
    },
    admission: {
      admissionProcess: "Entrance Based",
      entranceExams: ["TNEA"],
      applicationStartDate: new Date("2024-04-10"),
      applicationEndDate: new Date("2024-06-20"),
    },
    facilities: {
      hostel: true,
      transport: true,
      library: true,
      sports: false,
      wifi: true,
      placementCell: true,
    },
    placement: {
      placementPercentage: 88,
      averagePackage: 680000,
      highestPackage: 3200000,
      topRecruiters: ["ISRO", "DRDO", "BHEL", "L&T", "TATA Motors"],
    },
    media: {
      logo: "https://example.com/mit-logo.jpg",
      images: [
        "https://example.com/mit-campus.jpg",
        "https://example.com/mit-lab.jpg",
      ],
    },
    isActive: true,
    isVerified: true,
    createdAt: new Date("2023-02-15"),
    updatedAt: new Date("2024-01-21"),
  },
];

export const dummyCourses = [
  {
    _id: "course1",
    name: "B.Tech IT", // 👈 short name (CARD TITLE)
    degree: "Bachelor of Technology",
    level: "UG",
    category: "Engineering & Technology",
    specialization: "Information Technology",
    duration: 4,
    fees: { min: 150000, max: 300000 },
    intake: 120,
    entranceExams: ["JEE Main", "TNEA"],
    college: {
      _id: "college1",
      name: "Sri Ram Engineering College", // 👈 shown under course name
      type: "Private",
      establishedYear: 2008,
      location: {
        city: "Chennai",
        district: "Chennai",
        state: "Tamil Nadu",
      },
      accreditation: {
        naac: "A+",
        nba: true,
      },
      placement: {
        placementPercentage: 92,
        highestPackage: 1200000,
      },
      facilities: {
        hostel: true,
        placementCell: true,
        wifi: true,
        sports: true,
        transport: true,
      },
      admission: {
        entranceExams: ["JEE Main", "TNEA", "SRMEEE"],
      },
      media: {
        logo: "https://via.placeholder.com/100",
      },
    },
  },

  {
    _id: "course2",
    name: "B.Sc Physics",
    degree: "Bachelor of Science",
    level: "UG",
    category: "Arts & Science",
    specialization: "Physics",
    duration: 3,
    fees: { min: 45000, max: 90000 },
    intake: 60,
    entranceExams: ["University Entrance Test"],
    college: {
      _id: "college2",
      name: "St. Joseph’s College of Arts & Science",
      type: "Government",
      establishedYear: 1965,
      location: {
        city: "Coimbatore",
        district: "Coimbatore",
        state: "Tamil Nadu",
      },
      accreditation: {
        naac: "A",
        nba: false,
      },
      placement: {
        placementPercentage: 78,
        highestPackage: 600000,
      },
      facilities: {
        hostel: true,
        placementCell: true,
        wifi: true,
        sports: false,
        transport: true,
      },
      admission: {
        entranceExams: ["University Entrance Test"],
      },
      media: {
        logo: "",
      },
    },
  },
];
